version: '3.8'

services:
  api: 
    build: .
    user: node
    working_dir: /opt/app
    command: npm run start:dev
    volumes:
      - .:/opt/app
    networks:
      - borrow
    ports:
      - 4000:3000
    links:
      - postgres 
    depends_on:
      - postgres  
  postgres:
    image: postgres 
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 40102:5432
    networks:
      - borrow
  
networks:
  borrow:

volumes: 
  postgres:  